import { test, expect } from '@playwright/test'
import { pretest } from '../src/experiments/quiz/exp02.js'

test.use({ viewport: { width: 1440, height: 1100 } })
test.beforeEach(async ({ page }) => {
  await page.goto('/tests/fixtures/chess-pretest.html')
  await expect(page.getByRole('button', { name: 'LET’S PLAY' })).toBeVisible()
})

test('desktop: four squares, wrong branch, keyboard, drag, fullscreen, resume', async ({ page }) => {
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.screenshot({ path: 'test-results/chess-ready.png', fullPage: true })
  await page.getByRole('button', { name: 'LET’S PLAY' }).click()
  await expect(page.locator('.cc-answer')).toHaveCount(4)
  await expect(page.locator('.cc-square.is-target')).toHaveCount(4)
  await page.screenshot({ path: 'test-results/chess-playing.png', fullPage: true })
  const before = await page.locator('.cc-progress').getAttribute('aria-label')
  const blocked = await page.locator('[data-square="a1"]').boundingBox()
  await page.mouse.click(blocked.x + blocked.width / 2, blocked.y + blocked.height / 2)
  await expect(page.locator('.cc-progress')).toHaveAttribute('aria-label', before)
  const source = await page.locator('.cc-square.is-active').boundingBox()
  const destination = await page.locator('.cc-square[data-chess-choice="0"]').boundingBox()
  await page.mouse.move(source.x + source.width / 2, source.y + source.height / 2)
  await page.mouse.down()
  await page.mouse.move(destination.x + destination.width / 2, destination.y + destination.height / 2, { steps: 8 })
  await page.mouse.up()
  await expect(page.locator('.cc-progress')).toHaveAttribute('aria-label', '1 of 20 questions answered')
  await expect(page.locator('.cc-line-badge')).toHaveText('YOUR OWN LINE')
  await expect(page.locator('.cc-answer')).toHaveCount(4)
  await expect(page.locator('.cc-feedback')).toContainText('Not quite')
  await page.keyboard.press('4')
  await expect(page.locator('.cc-progress')).toHaveAttribute('aria-label', '2 of 20 questions answered')
  await expect(page.locator('.cc-answer')).toHaveCount(4)
  await page.getByRole('button', { name: 'Enter fullscreen' }).click()
  await expect(page.getByRole('button', { name: 'Exit fullscreen' })).toBeVisible()
  await page.getByRole('button', { name: 'Exit fullscreen' }).click()
  await expect(page.getByRole('button', { name: 'Enter fullscreen' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'RESUME GAME' }).click()
  await expect(page.locator('.cc-answer')).toHaveCount(4)
  await expect(page.locator('.cc-progress')).toHaveAttribute('aria-label', '2 of 20 questions answered')
  expect(errors).toEqual([])
})

test('all correct answers reach checkmate, persist 20/20 and allow a fresh replay', async ({ page }) => {
  test.setTimeout(60000)
  await page.getByRole('button', { name: 'LET’S PLAY' }).click()
  for (const [i, question] of pretest.entries()) {
    await expect(page.locator('.cc-question-copy h4')).toHaveText(question.prompt)
    await page.locator(`.cc-square[data-chess-choice="${question.answer}"]`).click()
    await expect(page.locator('.cc-progress')).toHaveAttribute('aria-label', `${i + 1} of 20 questions answered`)
  }
  await expect(page.getByRole('heading', { name: 'CHECKMATE!', exact: true })).toBeVisible()
  await expect(page.locator('.cc-result')).toContainText('20 / 20')
  await expect(page.locator('.cc-move-strip')).toContainText('Rh2#')
  await page.screenshot({ path: 'test-results/chess-checkmate.png', fullPage: true })
  await page.reload()
  await expect(page.locator('.cc-previous')).toContainText('20/20')
  await page.getByRole('button', { name: 'LET’S PLAY' }).click()
  await expect(page.locator('.cc-question-copy h4')).toHaveText(pretest[0].prompt)
  await expect(page.locator('.cc-progress')).toHaveAttribute('aria-label', '0 of 20 questions answered')
})

test('mobile: board and answers fit, tapping a destination submits exactly once', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'LET’S PLAY' }).click()
  await expect(page.locator('.cc-answer')).toHaveCount(4)
  await page.screenshot({ path: 'test-results/chess-mobile.png', fullPage: true })
  const dimensions = await page.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth }))
  expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.width)
  await page.locator('.cc-square.is-active').click()
  await page.locator('.cc-square[data-chess-choice="1"]').click()
  await expect(page.locator('.cc-progress')).toHaveAttribute('aria-label', '1 of 20 questions answered')
  await expect(page.locator('.cc-answer')).toHaveCount(4)
  await expect(page.locator('.cc-feedback')).toContainText('Correct. Nice move!')
})

test('real experiment route uses chess only for Experiment 2 pretest', async ({ page }) => {
  // Isolated browser-only API fixtures: no real student or database writes.
  const state = { cleared: { 1: { stars: 3 } }, tasks: {}, quizzes: {}, xp: 100, coins: 10, savedAt: Date.now() }
  await page.route('**/api/student/**', async (route) => {
    const url = route.request().url()
    await route.fulfill({ json: url.endsWith('/login')
      ? { token: 'isolated-browser-test', student: { id: 'CHESS-TEST', name: 'Chess Test', className: 'AIML-A' }, state }
      : { ok: true, state } })
  })
  await page.goto('/login/student')
  await page.getByLabel('ROLL NUMBER').fill('CHESS-TEST')
  await page.getByLabel('PASSWORD', { exact: true }).fill('fixture-only')
  await page.getByRole('button', { name: 'INSERT COIN & START' }).click()
  await expect(page).toHaveURL(/\/student\/?$/)
  await page.goto('/student/lab/2')
  await page.getByRole('button', { name: '3. Pretest', exact: true }).click()
  await expect(page.getByRole('button', { name: 'LET’S PLAY' })).toBeVisible()
  await page.getByRole('button', { name: 'LET’S PLAY' }).click()
  await expect(page.locator('.cc-square.is-target')).toHaveCount(4)
  await page.locator('.cc-stage').screenshot({ path: 'test-results/chess-in-app.png' })
  await page.getByRole('button', { name: '7. Posttest', exact: true }).click()
  await expect(page.locator('.cc-stage')).toHaveCount(0)
  await expect(page.locator('.lab-quiz')).toBeVisible()
  await page.goto('/student/lab/1')
  await page.getByRole('button', { name: '3. Pretest', exact: true }).click()
  await expect(page.locator('.cc-stage')).toHaveCount(0)
  await expect(page.locator('.race-stage')).toBeVisible()
})
